apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-username: bW9uZ291c2Vy  
  mongo-password: bW9uZ29wYXNzd29yZA==  
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy  
  mongo-pass: bW9uZ29wYXNzd29yZA==
  me-user: YWRtaW4=
  me-pass: cGFzc3dvcmQ=